'use client';

import { useState, useEffect, useCallback } from 'react';
import AdminNav from '@/components/AdminNav';

interface CardEntry {
  id:          number;
  name:        string;
  designation: string;
  phone:       string;
  createdAt:   string;
}

interface ApiResponse {
  entries:    CardEntry[];
  total:      number;
  page:       number;
  limit:      number;
  totalPages: number;
}

const LIMIT = 10;

const cell: React.CSSProperties = { padding: '13px 18px', fontSize: 14 };

export default function AdminDashboard() {
  const [data,        setData]        = useState<ApiResponse | null>(null);
  const [loading,     setLoading]     = useState(true);
  const [search,      setSearch]      = useState('');
  const [searchInput, setSearchInput] = useState('');
  const [page,        setPage]        = useState(1);

  const fetchEntries = useCallback(async () => {
    setLoading(true);
    try {
      const params = new URLSearchParams({
        page:  String(page),
        limit: String(LIMIT),
        ...(search ? { search } : {}),
      });
      const res  = await fetch(`/api/admin/entries?${params}`);
      const json = await res.json();
      setData(res.ok ? json : null);
    } catch {
      setData(null);
    } finally {
      setLoading(false);
    }
  }, [page, search]);

  useEffect(() => { fetchEntries(); }, [fetchEntries]);

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    setSearch(searchInput.trim());
    setPage(1);
  };

  const handleClear = () => {
    setSearchInput('');
    setSearch('');
    setPage(1);
  };

  const formatDate = (iso: string) =>
    new Date(iso).toLocaleString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit',
    });

  return (
    <div style={{ minHeight: '100vh', position: 'relative', zIndex: 1 }}>
      <AdminNav />

      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '36px 24px' }}>

        {/* Page header */}
        <div style={{ marginBottom: 32 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 4 }}>
            <span style={{ display: 'inline-block', width: 3, height: 22, background: '#C8102E', borderRadius: 2 }} />
            <h1 style={{ fontSize: 24, fontWeight: 800, color: '#1B3A6B', margin: 0 }}>
              Card Generations
            </h1>
          </div>
          <p style={{ color: '#9090AA', fontSize: 13, marginLeft: 13 }}>
            All personalised Eid cards generated by employees
          </p>
        </div>

        {/* Stats */}
        {data && (
          <div style={{ display: 'flex', gap: 16, marginBottom: 28, flexWrap: 'wrap' }}>
            <div
              className="lpl-card"
              style={{ padding: '18px 28px', minWidth: 180 }}
            >
              <p style={{ fontSize: 34, fontWeight: 900, color: '#C8102E', lineHeight: 1 }}>
                {data.total}
              </p>
              <p style={{ color: '#9090AA', fontSize: 13, marginTop: 5 }}>Total Cards Generated</p>
            </div>
            {search && (
              <div className="lpl-card" style={{ padding: '18px 28px', minWidth: 180 }}>
                <p style={{ fontSize: 34, fontWeight: 900, color: '#1B3A6B', lineHeight: 1 }}>
                  {data.entries.length}
                </p>
                <p style={{ color: '#9090AA', fontSize: 13, marginTop: 5 }}>
                  Results for &ldquo;{search}&rdquo;
                </p>
              </div>
            )}
          </div>
        )}

        {/* Search */}
        <form onSubmit={handleSearch} style={{ display: 'flex', gap: 10, marginBottom: 20 }}>
          <input
            id="search-input"
            type="text"
            className="lpl-input"
            placeholder="Search by name, designation or phone…"
            value={searchInput}
            onChange={(e) => setSearchInput(e.target.value)}
            style={{ flex: 1 }}
          />
          <button
            id="search-btn"
            type="submit"
            style={{
              background: 'linear-gradient(135deg, #C8102E, #A00D23)',
              color: '#fff',
              border: 'none',
              padding: '12px 22px',
              borderRadius: 10,
              fontWeight: 700,
              cursor: 'pointer',
              fontSize: 14,
              whiteSpace: 'nowrap',
              boxShadow: '0 4px 14px rgba(200,16,46,0.25)',
            }}
          >
            Search
          </button>
          {search && (
            <button
              id="clear-search-btn"
              type="button"
              onClick={handleClear}
              style={{
                background: 'rgba(255,255,255,0.8)',
                border: '1.5px solid #E4D9C4',
                color: '#4A4868',
                padding: '12px 20px',
                borderRadius: 10,
                fontWeight: 600,
                cursor: 'pointer',
                fontSize: 14,
              }}
            >
              Clear
            </button>
          )}
        </form>

        {/* Table */}
        <div className="lpl-card" style={{ overflow: 'hidden' }}>
          {loading ? (
            <div style={{ textAlign: 'center', padding: 64, color: '#C8960C' }}>
              <div
                style={{
                  width: 36, height: 36, border: '3px solid #E4D9C4',
                  borderTopColor: '#C8102E', borderRadius: '50%',
                  margin: '0 auto 16px',
                  animation: 'spin 0.8s linear infinite',
                }}
              />
              <p style={{ color: '#9090AA', fontSize: 14 }}>Loading entries…</p>
              <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
            </div>
          ) : !data?.entries?.length ? (
            <div style={{ textAlign: 'center', padding: 64 }}>
              <div style={{
                width: 52, height: 52, borderRadius: 14,
                background: 'rgba(200,150,12,0.08)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                margin: '0 auto 16px',
              }}>
                <span style={{ fontSize: 26 }}>📭</span>
              </div>
              <p style={{ color: '#4A4868', fontWeight: 600, fontSize: 15 }}>
                {search ? 'No entries found' : 'No cards generated yet'}
              </p>
              <p style={{ color: '#9090AA', fontSize: 13, marginTop: 4 }}>
                {search ? `No results for "${search}"` : 'Entries will appear here once users generate cards'}
              </p>
            </div>
          ) : (
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr style={{ borderBottom: '1.5px solid rgba(200,150,12,0.18)', background: 'rgba(200,150,12,0.04)' }}>
                    {['#', 'Name', 'Designation', 'Phone', 'Date Generated'].map((h) => (
                      <th
                        key={h}
                        style={{
                          ...cell,
                          textAlign: 'left',
                          color: '#1B3A6B',
                          fontWeight: 700,
                          fontSize: 11.5,
                          letterSpacing: 0.6,
                          textTransform: 'uppercase',
                        }}
                      >
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {data.entries.map((entry, idx) => (
                    <tr
                      key={entry.id}
                      style={{ borderBottom: '1px solid rgba(200,150,12,0.08)', transition: 'background 0.12s' }}
                      onMouseEnter={(e) => (e.currentTarget.style.background = 'rgba(200,150,12,0.04)')}
                      onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
                    >
                      <td style={{ ...cell, color: '#C0C0D0', fontWeight: 600 }}>
                        {(page - 1) * LIMIT + idx + 1}
                      </td>
                      <td style={{ ...cell, color: '#1B3A6B', fontWeight: 700 }}>
                        {entry.name}
                      </td>
                      <td style={{ ...cell, color: '#4A4868' }}>
                        {entry.designation}
                      </td>
                      <td style={{ ...cell, color: '#4A4868' }}>
                        {entry.phone}
                      </td>
                      <td style={{ ...cell, color: '#9090AA', fontSize: 13 }}>
                        {formatDate(entry.createdAt)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Pagination */}
        {data && data.totalPages > 1 && (
          <div style={{ display: 'flex', justifyContent: 'center', gap: 6, marginTop: 20, flexWrap: 'wrap', alignItems: 'center' }}>
            <button
              id="prev-page-btn"
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page <= 1}
              style={{
                padding: '9px 18px', borderRadius: 9, fontSize: 13, fontWeight: 600,
                background: page <= 1 ? '#F5F5F5' : '#fff',
                border: '1.5px solid #E4D9C4',
                color: page <= 1 ? '#C0C0D0' : '#4A4868',
                cursor: page <= 1 ? 'not-allowed' : 'pointer',
              }}
            >
              ← Prev
            </button>

            {Array.from({ length: data.totalPages }, (_, i) => i + 1)
              .filter((p) => p === 1 || p === data!.totalPages || Math.abs(p - page) <= 2)
              .map((p, i, arr) => (
                <span key={p} style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                  {i > 0 && arr[i - 1] !== p - 1 && (
                    <span style={{ color: '#C0C0D0' }}>…</span>
                  )}
                  <button
                    id={`page-btn-${p}`}
                    onClick={() => setPage(p)}
                    style={{
                      padding: '9px 15px', borderRadius: 9, fontSize: 13,
                      background: p === page ? 'linear-gradient(135deg, #C8102E, #A00D23)' : '#fff',
                      border: p === page ? 'none' : '1.5px solid #E4D9C4',
                      color: p === page ? '#fff' : '#4A4868',
                      fontWeight: p === page ? 700 : 500,
                      cursor: 'pointer',
                      boxShadow: p === page ? '0 3px 10px rgba(200,16,46,0.25)' : 'none',
                    }}
                  >
                    {p}
                  </button>
                </span>
              ))}

            <button
              id="next-page-btn"
              onClick={() => setPage((p) => Math.min(data!.totalPages, p + 1))}
              disabled={page >= data.totalPages}
              style={{
                padding: '9px 18px', borderRadius: 9, fontSize: 13, fontWeight: 600,
                background: page >= data.totalPages ? '#F5F5F5' : '#fff',
                border: '1.5px solid #E4D9C4',
                color: page >= data.totalPages ? '#C0C0D0' : '#4A4868',
                cursor: page >= data.totalPages ? 'not-allowed' : 'pointer',
              }}
            >
              Next →
            </button>
          </div>
        )}

        {data?.entries && !loading && (
          <p style={{ textAlign: 'center', marginTop: 14, color: '#B0B0C8', fontSize: 13 }}>
            Showing {data.entries.length} of {data.total} entries
            {search && ` for "${search}"`}
          </p>
        )}
      </div>
    </div>
  );
}
