'use client';

import { useState, useEffect, useCallback } from 'react';
import AdminNav from '@/components/AdminNav';

interface CardEntry {
    id: number;
    name: string;
    designation: string;
    phone: string;
    createdAt: string;
}

interface ApiResponse {
    entries: CardEntry[];
    total: number;
    page: number;
    limit: number;
    totalPages: number;
}

const LIMIT = 10;

export default function AdminDashboard() {
    const [data, setData] = useState<ApiResponse | null>(null);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');
    const [searchInput, setSearchInput] = useState('');
    const [page, setPage] = useState(1);

    const fetchEntries = useCallback(async () => {
        setLoading(true);
        try {
            const params = new URLSearchParams({
                page: String(page),
                limit: String(LIMIT),
                ...(search ? { search } : {}),
            });
            const res = await fetch(`/api/admin/entries?${params}`);
            const json = await res.json();
            setData(json);
        } catch {
            console.error('Failed to fetch entries');
        } finally {
            setLoading(false);
        }
    }, [page, search]);

    useEffect(() => {
        fetchEntries();
    }, [fetchEntries]);

    const handleSearch = (e: React.FormEvent) => {
        e.preventDefault();
        setSearch(searchInput.trim());
        setPage(1);
    };

    const handleClearSearch = () => {
        setSearchInput('');
        setSearch('');
        setPage(1);
    };

    const formatDate = (iso: string) => {
        const d = new Date(iso);
        return d.toLocaleString('en-GB', {
            day: '2-digit',
            month: 'short',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        });
    };

    return (
        <div style={{ minHeight: '100vh' }}>
            <AdminNav />

            <div style={{ maxWidth: 1200, margin: '0 auto', padding: '32px 24px' }}>
                {/* Page Header */}
                <div style={{ marginBottom: 32 }}>
                    <h1 style={{ fontSize: 28, fontWeight: 800, color: '#d4a017', marginBottom: 4 }}>
                        📊 Card Generations
                    </h1>
                    <p style={{ color: 'rgba(255,255,255,0.45)', fontSize: 14 }}>
                        All personalized Eid cards generated by users
                    </p>
                </div>

                {/* Stats Row */}
                {data && (
                    <div
                        style={{
                            display: 'grid',
                            gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
                            gap: 16,
                            marginBottom: 28,
                        }}
                    >
                        <div
                            className="glass-card"
                            style={{ padding: '20px 24px', textAlign: 'center' }}
                        >
                            <p style={{ fontSize: 36, fontWeight: 800, color: '#d4a017' }}>{data.total}</p>
                            <p style={{ color: 'rgba(255,255,255,0.5)', fontSize: 13, marginTop: 4 }}>Total Cards Generated</p>
                        </div>
                    </div>
                )}

                {/* Search Bar */}
                <form onSubmit={handleSearch} style={{ display: 'flex', gap: 12, marginBottom: 24 }}>
                    <input
                        id="search-input"
                        type="text"
                        className="eid-input"
                        placeholder="Search by name, designation, or phone..."
                        value={searchInput}
                        onChange={(e) => setSearchInput(e.target.value)}
                        style={{ flex: 1 }}
                    />
                    <button
                        id="search-btn"
                        type="submit"
                        style={{
                            background: 'linear-gradient(135deg, #d4a017, #f0c040)',
                            color: '#0f2d1e',
                            border: 'none',
                            padding: '12px 24px',
                            borderRadius: 12,
                            fontWeight: 700,
                            cursor: 'pointer',
                            whiteSpace: 'nowrap',
                            fontSize: 14,
                        }}
                    >
                        🔍 Search
                    </button>
                    {search && (
                        <button
                            id="clear-search-btn"
                            type="button"
                            onClick={handleClearSearch}
                            style={{
                                background: 'rgba(255,255,255,0.08)',
                                border: '1px solid rgba(255,255,255,0.2)',
                                color: 'rgba(255,255,255,0.7)',
                                padding: '12px 20px',
                                borderRadius: 12,
                                cursor: 'pointer',
                                fontSize: 14,
                            }}
                        >
                            ✕ Clear
                        </button>
                    )}
                </form>

                {/* Table */}
                <div className="glass-card" style={{ overflow: 'hidden' }}>
                    {loading ? (
                        <div style={{ textAlign: 'center', padding: 60, color: 'rgba(255,255,255,0.4)' }}>
                            <div style={{ fontSize: 32 }}>⏳</div>
                            <p style={{ marginTop: 12 }}>Loading entries...</p>
                        </div>
                    ) : !data || data.entries.length === 0 ? (
                        <div style={{ textAlign: 'center', padding: 60, color: 'rgba(255,255,255,0.4)' }}>
                            <div style={{ fontSize: 40 }}>📭</div>
                            <p style={{ marginTop: 12 }}>
                                {search ? 'No entries found for your search.' : 'No cards generated yet.'}
                            </p>
                        </div>
                    ) : (
                        <div style={{ overflowX: 'auto' }}>
                            <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                                <thead>
                                    <tr
                                        style={{
                                            borderBottom: '1px solid rgba(212, 160, 23, 0.2)',
                                            background: 'rgba(212, 160, 23, 0.05)',
                                        }}
                                    >
                                        {['#', 'Name', 'Designation', 'Phone', 'Date Generated'].map((h) => (
                                            <th
                                                key={h}
                                                style={{
                                                    padding: '14px 20px',
                                                    textAlign: 'left',
                                                    color: '#d4a017',
                                                    fontWeight: 600,
                                                    fontSize: 13,
                                                    letterSpacing: '0.5px',
                                                    textTransform: 'uppercase',
                                                }}
                                            >
                                                {h}
                                            </th>
                                        ))}
                                    </tr>
                                </thead>
                                <tbody>
                                    {data.entries.map((entry, idx) => (
                                        <tr
                                            key={entry.id}
                                            style={{
                                                borderBottom: '1px solid rgba(255,255,255,0.06)',
                                                transition: 'background 0.15s ease',
                                            }}
                                            onMouseEnter={(e) =>
                                                (e.currentTarget.style.background = 'rgba(255,255,255,0.04)')
                                            }
                                            onMouseLeave={(e) => (e.currentTarget.style.background = 'transparent')}
                                        >
                                            <td style={{ padding: '14px 20px', color: 'rgba(255,255,255,0.35)', fontSize: 13 }}>
                                                {(page - 1) * LIMIT + idx + 1}
                                            </td>
                                            <td style={{ padding: '14px 20px', color: '#fff', fontWeight: 500 }}>
                                                {entry.name}
                                            </td>
                                            <td style={{ padding: '14px 20px', color: 'rgba(255,255,255,0.65)' }}>
                                                {entry.designation}
                                            </td>
                                            <td style={{ padding: '14px 20px', color: 'rgba(255,255,255,0.65)' }}>
                                                {entry.phone}
                                            </td>
                                            <td style={{ padding: '14px 20px', color: 'rgba(255,255,255,0.4)', fontSize: 13 }}>
                                                {formatDate(entry.createdAt)}
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>

                {/* Pagination */}
                {data && data.totalPages > 1 && (
                    <div
                        style={{
                            display: 'flex',
                            justifyContent: 'center',
                            gap: 8,
                            marginTop: 24,
                            flexWrap: 'wrap',
                            alignItems: 'center',
                        }}
                    >
                        <button
                            id="prev-page-btn"
                            onClick={() => setPage((p) => Math.max(1, p - 1))}
                            disabled={page <= 1}
                            style={{
                                padding: '10px 20px',
                                borderRadius: 10,
                                background: page <= 1 ? 'rgba(255,255,255,0.04)' : 'rgba(255,255,255,0.09)',
                                border: '1px solid rgba(255,255,255,0.15)',
                                color: page <= 1 ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.7)',
                                cursor: page <= 1 ? 'not-allowed' : 'pointer',
                                fontSize: 14,
                            }}
                        >
                            ← Prev
                        </button>

                        {Array.from({ length: data.totalPages }, (_, i) => i + 1)
                            .filter((p) => p === 1 || p === data!.totalPages || Math.abs(p - page) <= 2)
                            .map((p, i, arr) => (
                                <span key={p}>
                                    {i > 0 && arr[i - 1] !== p - 1 && (
                                        <span style={{ color: 'rgba(255,255,255,0.25)', padding: '0 4px' }}>…</span>
                                    )}
                                    <button
                                        id={`page-btn-${p}`}
                                        onClick={() => setPage(p)}
                                        style={{
                                            padding: '10px 16px',
                                            borderRadius: 10,
                                            background: p === page ? 'linear-gradient(135deg, #d4a017, #f0c040)' : 'rgba(255,255,255,0.06)',
                                            border: p === page ? 'none' : '1px solid rgba(255,255,255,0.12)',
                                            color: p === page ? '#0f2d1e' : 'rgba(255,255,255,0.6)',
                                            fontWeight: p === page ? 700 : 400,
                                            cursor: 'pointer',
                                            fontSize: 14,
                                        }}
                                    >
                                        {p}
                                    </button>
                                </span>
                            ))}

                        <button
                            id="next-page-btn"
                            onClick={() => setPage((p) => Math.min(data!.totalPages, p + 1))}
                            disabled={page >= data.totalPages}
                            style={{
                                padding: '10px 20px',
                                borderRadius: 10,
                                background: page >= data.totalPages ? 'rgba(255,255,255,0.04)' : 'rgba(255,255,255,0.09)',
                                border: '1px solid rgba(255,255,255,0.15)',
                                color: page >= data.totalPages ? 'rgba(255,255,255,0.2)' : 'rgba(255,255,255,0.7)',
                                cursor: page >= data.totalPages ? 'not-allowed' : 'pointer',
                                fontSize: 14,
                            }}
                        >
                            Next →
                        </button>
                    </div>
                )}

                {data && !loading && (
                    <p style={{ textAlign: 'center', marginTop: 16, color: 'rgba(255,255,255,0.3)', fontSize: 13 }}>
                        Showing {data.entries.length} of {data.total} entries
                        {search && ` for "${search}"`}
                    </p>
                )}
            </div>
        </div>
    );
}
